### ISSUE TITLE
add a "commit" button to the popup

### ISSUE THREAD

**Issue by Haroenv** [StenographyDev/autopilot-vsc#4]
When I want to read a longer explanation, I'd rather read it inline as a comment than a popup, but running the autopilot again will give different results

**Comment by bramses** [comment]
Addressed in 1.1.3: https://github.com/StenographyDev/autopilot-vsc/commit/49e43106ffa4d59548ba2d82ac51e5c32649a7e8#diff-cfee35839ea223905ca775df0900b4dd24e08a316b06d8ccd05dcc5e40989cfb
