### ISSUE TITLE
Should the name be different?

### ISSUE THREAD

**Issue by Haroenv** [StenographyDev/autopilot-vsc#6]
It doesn't help you drive (code), but it helps you read. Names I thought of:

- steno explain
- stenography glasses
- steno lens
- steno map

imo the name stenography is also a little long, maybe steno would do?

**Comment by bramses** [comment]
Upon further reflection, I've decided to keep the name. `Autopilot` isn't so much that the developer is having an "autopilot" experience, but the parser layer is running the *Stenography* layer automatically, as opposed to developers running it manually on self chosen code blocks.

As for `Steno`, I call it that a lot based on parlance, but the business is registered and trademarked as Stenography :)
